<!DOCTYPE HTML>
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>
    <div class="container ">
        <a href="registerUser.php">
            <img src="images/backBtn.png" alt="HTML tutorial" style="width:150px;height:50px;">
        </a>
    <br>
    <br>
        <div class="row justify-content-center">
            <input class="btn-primary" type="file" onchange="previewFile()" id="fileButton">
        </div>
        <br>
    <h6 class="text-center">SELECTED IMAGE WILL APPEAR HERE</h6>
    <div class="row justify-content-center">
        <img class="border border-dark" src="" id="previewImage" height="200" alt="Image preview...">
    </div>
    <br>
    <div class="border border-success">
        <h6 class="text-center"> Crop the image by moving on X-axis (Left-Right) or Y-axis (Up-Down) - CROP PREVIEW </h6>
            <div class="row mr-5 justify-content-center">
                <div class="row  justify-content-center">
                    <label class="mt-5">Y axis</label>
                    <input type="range" id="y" min="-100" max="" value="100" step="1"  onchange="crop()" style="transform: rotate(90deg); !important;">
                    <!-- <img class="" src="" id="previewImage" height="200" alt="Image preview..."> -->
                    <canvas class="border border-dark" id="myCanvas" width="200" height="200"></canvas>
                </div>
            </div>
            <div class="row ml-5 justify-content-center">
                <input type="range" id="x" min="-100" max="500"  onchange="crop()">
                <label>X axis</label>
            </div>
    </div>
        </br>
        <h6 class="text-center">Download the image which is cropped and resized to "200x200", the best size to upload on this website!</h6>
        <div class="row justify-content-center">
            <button onclick="canvasDownload()">Download Cropped Image</button>
        </div>
            <!-- <img src="" id="previewImage" height="200" alt="Image preview..."> -->
    </div>
    <script>
        //document.getElementById("y").style.transform = "rotate('90deg')";
    </script>
    <script src="js/imageTool.js"></script>

  </body>
</html>