<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="css/my-style.css">
    <script src="js/websiteValidations.js"></script>
</head>
<body>
    <div class="container">
        <div class="content">
            <h1>Login</h1>
            <hr />
            <div class="row">
                <!-- this FORM is used to get user login details and process it accordingly -->
                <form action="" method="POST" class="bg-light">
                    <div class="p-5">
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" id="email" name="email" placeholder="Enter your email address" onfocusout="validateEmail(this.value)" required >
                    </div>
                        <div id="emailWarnings"></div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password" placeholder="Enter your password" required>
                    </div>
                    <button type="submit" id="loginButton" class="btn-primary rounded m-1 p-2">Login</button>
                    </div>
                </form>
            </div>
            <hr/>
            <div class="text-center">
                <h4 class="">Not Registered yet? Sign up now!</h4>
                <br/>
                <a href="registerUser.php" class="btn-primary rounded m-1 p-2">Sign Up</a>
            </div>
            <hr />
            <a href="selfAssessment.pdf" >For the self-assessment document click here!</a>
            <hr />
            <div id="searchInfo">
                <h1 class="row justify-content-center">Search Registered Users</h1>
                <form action="" method="GET" >
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search..." name="txtSearch" id="txtSearch"/>
                                <div class="input-group-btn">
                                    <button class="btn btn-primary" type="submit" name="submitSearch" value="Searched">
                                        <span class="glyphicon glyphicon-search"> Search</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <?php
                //show search results

                //echo '<div><br/>Users Found: '.$userCount.'</br></div>';
                //var_dump($userCount);
                if(!empty($resultRows))
                {
                    $userCount=count($resultRows);
                    //$userCount=count($resultRows);
                    echo '<div><br/>Users Found by Search: '.$userCount.'</br></div>';
                    foreach ($resultRows as $row) {
                        echo '<div class="row justify-content-center warning" id ="profileList">
                                <div class="row justify-content-center  col-lg-6"><span>' .$row['username']. '</span></div>
                                <div class="row justify-content-center  col-lg-6"><img src="' .$row['userImage']. '" height="50" width="50" alt="Profile image"></div>
                                </div>';
                    }
                }
                ?>
            </div>
            <h3 class="row justify-content-center">All Users</h3>
            <div class="profileContent">
                <?php
                $userCount=count($allUsers);
                //var_dump($userCount);
                echo '<div>Registered Users: '.$userCount.'</div>';
                if($allUsers)
                {
                    foreach ($allUsers as $row){
                        echo '<div class="row justify-content-center alert-info" id="profileList">
                                <div class="row justify-content-center  col-lg-6"><span>' .$row->getUsername(). '</span></div>
                                <div class="row justify-content-center  col-lg-6"><img src="' .$row->getUserImage() . '" height="50" width="50" alt="Profile image"></div>
                                </div>';
                    }
                }
                else
                {
                    echo '<h4>No users registered!</h4>';
                }
                ?>
            </div>
        </div>
    </div>
    <script src="js/liveSearch.js"></script>
</body>
</html>

