<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="css/my-style.css">
    <script src="js/websiteValidations.js"></script>
    <title>Signup | Register</title>
</head>
<body>
    <div class="div-center">
        <div class="content">
            <h1>Signup</h1>
            <hr />
            <form action="" method="POST" enctype="multipart/form-data">
                <!--enctype="multipart/form-data"-->
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="username" id="username" name="username" spellcheck="false" placeholder="Enter your username" onkeyup="validateUsername(this.value)" onfocusout="validateUsername(this.value)" required>
                </div>
                <div id="usernameWarnings"></div>
                <div class="form-group">
                    <label for="fName">First Name:</label>
                    <input type="text" id="fName" name="fName" spellcheck="false" placeholder="Enter your First Name" onfocusout="validateFirstName(this.value)" required>
                </div>
                <div id="firstNameWarnings"></div>
                <div class="form-group">
                    <label for="lName">Last Name:</label>
                    <input type="text" id="lName" name="lName" spellcheck="false" placeholder="Enter your Last Name" onfocusout="validateLastName(this.value)" required>
                </div>
                <div id="lastNameWarnings"></div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" id="email" name="email" spellcheck="false" placeholder="Enter your email address" onfocusout="validateEmail(this.value)" required>
                </div>
                <div id="emailWarnings"></div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="passwordA" name="passwordA" placeholder="Enter your password" onfocusout="validatePassword(this.value)" required>
                </br>
                    <input type="password" id="password" name="password" placeholder="Re-Enter your password" onfocusout="validatePassword(this.value)" required>
                    <small class="form-text text-muted">NOTE: Password must be 6 or more characters!</small>
                </div>
                <div id="passwordWarnings"></div>
                <div class="form-group">
                    <label class="form-label" for="fileToUploadLabel">Profile Picture</label>
                    <input type="file" name="fileToUpload" id="fileToUpload" class="form-control" >
                    <small class="form-text text-muted">NOTE: if no image is uploaded, a random one will be assigned!</small>
                </div>
                <button type="submit" name="submit" id="signUpButton" class="btn-primary p-2 m-1">Sign up</button>
                <hr />
                <a href="index.php" >Already registered? login</a>
                <hr />
                <a href="imageTool.php" >Want to crop and resize an image to upload? Click here!</a>
            </form>
        </div>
    </div>
</body>
</html>

