<?php
require 'Views/template/header.phtml'
?>

<form action="friendFunctions.php?id=<?php echo $viewID; ?>" method="POST">
    <?php
        //$frnd_obj->isAlreadyFriend($viewID, $currentUserID);
        switch ($friendObj->isAlreadyFriend($viewID, $currentUserID))
        {
            case 1:
                echo '<div class="row justify-content-center ">';
                echo "<button type='submit' name='sndRequest' class='btn-primary m-3 p-3'>Send Friend Request</button>";
                echo '</div>';
                break;
            case 2:
                //$friendData=$friendObj->findUserById($viewID);
                echo '<div class="container  mt-5 mb-5 rounded pt-1" >
                      <div class="card alert-info mt-5 rounded pt-5 text-center">
                      <h6 class="card-title row justify-content-center display-4 alert-success rounded-pill">Friend Details</h6>
                      <h1 class="card-text col-lg-12 border-top border-light">Email: '.$userData['email'].'</h1>
                      <h1 class="card-text col-lg-12 border-top border-light">Username: '.$userData['username'].'</h1>
                      <h1 class="card-text col-lg-12 border-top border-light">Name: '.$userData['firstName'].' '.$userData['lastName'].'</h1>
                      <h1 class="card-text col-lg-12 border-top border-bottom border-light">Location: ('.$userData['lat'].', '.$userData['lng'].')</h1>
                      <h3 class="p-3"><button type="submit" name="rmvFriend" class="btn-danger col-xs-6 rounded">Remove Friend</button></h3>
                      </div></div>';
                break;
            case 3:
                echo "<h6 class='row justify-content-center display-4 alert-warning'>PENDING...</h6>";
                break;
        }
    ?>
</form>
</body>
</html>