<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php
        //html special chars function is used, so that it is interpreted as content and not HTML code
        //html special chars function prevents XSS(Cross site scripting) hacks
        echo htmlspecialchars($userData['username']); ?>
    </title>
    <!-- using the CDN (Content Delivery Network) bootstrap because it provides Faster loading speed
     by lowering the cost of bandwidth, amount of data that moves between the user and server reduces -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="css/my-style.css">
    <!-- <script src="js/OpenLayers-2.13.1/OpenLayers-2.13.1/OpenLayers.js"></script>
    <script src="js/userLocation.js"></script> -->

</head>
<body>
    <div class="container" id="profile">
        <div class="row border-left border-right border-success rounded-pill m-3">
            <div class="img col-lg-12 justify-content-center">
                <img src="<?php echo $userData['userImage'];?>" height="200" width="200"  alt="Profile image" >
            </div>
            <div class="col-lg-12 justify-content-center">
                <h1><?php echo $userData['firstName']." ".$userData['lastName'];?></h1>
            </div>
            <div class="col-lg-12 justify-content-center">
                <h1><?php echo $userData['email'];?></h1>
            </div>
            <div class="col-lg-12 justify-content-center">
                <h1><?php echo $userData['username'];?></h1>
            </div>
        </div>
        <nav class="row justify-content-center bg-light p-4">
                    <a href="profile.php" class="btn-primary rounded col-sm-3 m-1 p-3 text-decoration-none">Home</a>
                    <a href="requests.php" class="btn-primary rounded col-sm-3 m-1 p-3 text-decoration-none">
                        Requests <span class="badge badge-light alert-success"><?php echo $reqNumber;  ?></span>
                        <!-- I have used the sr only class, for screen readers, for accessibility -->
                        <span class="sr-only">unread messages</span>
                    </a>
                    <a href="userList.php" class="btn-primary rounded col-sm-3 m-1 p-3 text-decoration-none">All Users</a>
                    <a href="logout.php" class="btn-danger rounded col-sm-3 mt-5 p-3 text-decoration-none rounded-pill">Logout</a>
        </nav>

</div>
